### ISSUE TITLE
Update to Grails 2.5.x ?

### ISSUE THREAD

**Issue by mnellemann** [rodolfojcj/grails-adminlte-ui#2]
Hi,

Would it be possible to update this plugin to support Grails 2.5.x ?

````
Compilation error: startup failed:
 ..../target/work/plugins/jquery-1.10.2/src/groovy/org/codehaus/groovy/grails/plugins/jquery/JQueryConfig.groovy: 19: unable to resolve class org.codehaus.groovy.grails.commons.ApplicationHolder
 @ line 19, column 1.
   import org.codehaus.groovy.grails.commons.ApplicationHolder
   ^

1 error
````

**Comment by rodolfojcj** [comment]
Hi!

These days I'm dedicated to another project, but having a little time available I will review the reported error to fix it.

Thanks for reporting the issue.

**Comment by rodolfojcj** [comment]
Hello!

After reviewing your reported issue, I think it's related to the configuration of your project and not directly to the adminlte-ui plugin itself. It seems to me your _grails-app/conf/BuildConfig.groovy_ file is using jquery plugin version 1.10.2, which depends on the _org.codehaus.groovy.grails.commons.ApplicationHolder_ and this class has been removed from Grails 2.4, as stated on https://grails.github.io/grails-doc/2.4.x/guide/upgradingFrom23.html

My suggestion is to use a newer version of jquery plugin and also to use the _resources_ plugin, because _platform-core_ plugin depends on it. The plugins section of your _grails-app/conf/BuildConfig.groovy_ would look like this:

```groovy
    plugins {
      ////
      compile ":asset-pipeline:2.1.5"
      ////
      runtime ":jquery:1.11.1"
      runtime ':resources:1.2.14'
      runtime ':adminlte-ui:0.1.0'
    }
```
Please try again and tell us your results.
